### ISSUE TITLE
Construct a big dataset

### ISSUE THREAD

**Issue by RadouaneK** [Evercam-ML/SRGAN#1]
Since GANs in general need to be trained on very big datasets, your first task is to construct pairs of low and high resolution images of at least 100,000 pairs

- make sure you crop from random different regions of images from all available cameras
- crop images with 360x360 resolution and use openCV functions to downscale the image to 90x90
- use proper naming for the pair images, ex: img_001_lr, img_001_hr

**Comment by AqsaYousaf** [comment]
Thank you..I'll follow your suggestions
